### ISSUE TITLE
Issues #1

### ISSUE THREAD

**Issue by walterggomez** [Gonzalosanto/EstrD2023s1#1]
Hola Gonzalo tu código no compila 
WinHugs me marca lo siguiente en tu código

Hugs> :load "C:\\Users\\prida\\Desktop\\Repositorios\\EstrD2023s1Colabo\\GonzaSantaCruzTp1.hs"
ERROR file:.\GonzaSantaCruzTp1.hs:166 - Unrecognised character `\128' in column 2

Tenes hasta el 23-03-2022 para corregirlo.
Saludos Walter

**Comment by Gonzalosanto** [comment]
Hola Walter, desconozco ese tipo de error a que se puede deber. A mi WinHugs me compila perfectamente el archivo practica_1.hs. El error que veo por ahi se debe a un problema de formato o a que sobra una linea en blanco al final del archivo.

**Comment by walterggomez** [comment]
Gonzalo el error por el cual no me compila  viene por aca

data TipoDePokemon = Agua | Fuego | Planta deriving (Eq, Show)

esDeMismoTipo :: TipoDePokemon -> Pokemon -> Int
esDeMismoTipo Agua (Pok Agua _) = 1
esDeMismoTipo Fuego (Pok Fuego _) = 1
esDeMismoTipo Planta (Pok Planta _) = 1
esDeMismoTipo x y = 0

te tiro una pista fíjate los argumentos y la firma de la función

**Comment by Gonzalosanto** [comment]
Acabo de pushear unos cambios al codigo. Te aviso por si queres pullear de la rama master.

**Comment by walterggomez** [comment]
Es correcto como no se pide usar Eq no lo deberías usar, hasta que no se indique
Ahora si compila. 
Mas tarde te envió los Issues referidos al código , hay lugares donde haces doble Pattern Matching (PM) y lugares donde podes hacer subtareas que no lo estas haciendo.

**Comment by Gonzalosanto** [comment]
Dale buenisimo!
